name: KPSS Api
on:
  push:
    branches:
      [
        master,
        0.0.1-data-modelling,
        0.0.2-data-access-layer,
        0.0.3-data-query-layer,
      ]

  pull_request:
    branches:
      [
        master,
        0.0.1-data-modelling,
        0.0.2-data-access-layer,
        0.0.3-data-query-layer,
      ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
